### ISSUE TITLE
`createHomeWidget` called twice

### ISSUE THREAD

**Issue by Nealsoni00** [InvictusApps/foundation_flutter#2]
firebase & FCM initialized in createHomeWidget are called twice -- I think this is an expensive operation

![image](https://user-images.githubusercontent.com/7013191/124779367-b8087e80-df0f-11eb-9cdd-02320e0eea1d.png)

**Comment by Nealsoni00** [comment]
I think this only happens during hot-reload -- in which case we can probably ignore it

**Comment by Nealsoni00** [comment]
Never mind, happens during tab switching when u click the admin tab a fresh start. It causes a flash on every tab switch (preventing animation). 
![image](https://user-images.githubusercontent.com/7013191/124781340-52b58d00-df11-11eb-9e29-d2714941e9e1.png)

**Comment by darkfrog26** [comment]
Very strange. I'll look into it.
