### ISSUE TITLE
Safe Area iOS issue

### ISSUE THREAD

**Issue by Nealsoni00** [InvictusApps/foundation_flutter#4]
Views should go by default into the safe area (imo) or have some sort of way to set if a view should be allowed to expand into the safe area. (if this is already supported lmk)

![IMG_6784](https://user-images.githubusercontent.com/7013191/125525602-f67cf06b-7675-478d-b220-349c8905551a.PNG)

**Comment by darkfrog26** [comment]
This is not currently supported but should be fairly easily added. Is a per-screen flag sufficient so that each screen can decide whether the safe area should be honored?

**Comment by Nealsoni00** [comment]
Yea sure -- with honoring it being false by default

**Comment by darkfrog26** [comment]
Really? I would think honoring the safe area would always be the norm?
